#!/bin/bash
# Copyright (C) 2021 MyGpack

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# error precaution.
set -e

disp () {
    echo "-----> $*"
}

indent () {
    sed -u 's/^/       /'
}

_done () {
    echo -e "Done\n" | indent
}

_displaylogo () {
    echo '
===========================================

  ▄████  ██▓███   ▄▄▄       ▄████▄   ██ ▄█▀
 ██▒ ▀█▒▓██░  ██▒▒████▄    ▒██▀ ▀█   ██▄█▒ 
▒██░▄▄▄░▓██░ ██▓▒▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ 
░▓█  ██▓▒██▄█▓▒ ▒░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ 
░▒▓███▀▒▒██▒ ░  ░ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄
 ░▒   ▒ ▒▓▒░ ░  ░ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒
  ░   ░ ░▒ ░       ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░
░ ░   ░ ░░         ░   ▒   ░        ░ ░░ ░ 
      ░                ░  ░░ ░      ░  ░   
                           ░               
===========================================
|            VERSION  v0.1.0              |
|    By: @midnightmadwalk and code-rgb    |
|           (C) 2021 - USERGE-X           |
===========================================
'
}

get_branch () {
    local branch
    if [[ $PREF_BRANCH ]]
    then
        branch=$(echo $PREF_BRANCH | xargs)
    else
        branch=main
    fi
    echo $branch
}

get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO =~ $regex ]]
    then 
        echo "${UPSTREAM_REPO}"
    else
        echo "$(echo "aHR0cHM6Ly9naXRodWIuY29tL1NpeWFuMTIzL1Zlbm9teA==" | base64 -d)"
    fi
}

_setup_repo () {
    disp "Fetching Upstream Repo"
    git clone -q -b "$(get_branch)" "$(get_repolink)" VX
    _done
}

_startbot () {
    cd VX
    echo -e ">><< --- >><<  Starting [Venom-X]  >><< --- >><<\n" | indent
    bash run
}

begin_x () {
    _displaylogo
    sleep 5
    _setup_repo
    _startbot
}

begin_x
